Add asio coroutine support
pernatiy/asio-dbus pull request #1
Opened 2021-08-30 10:00 UTC by yurp

2021-08-31 10:13 UTC, zagrichanskiy requested changes

2021-08-31 10:13 UTC, zagrichanskiy commented on CMakeLists.txt
> +target_compile_features(asio-dbus INTERFACE cxx_std_20)
library is headeronly, so this should be enabled only for tests executable

2021-08-31 10:13 UTC, zagrichanskiy commented on include/dbus/connection_service.hpp
> +      detail::async_send_op<handler_type>(this->get_io_context(), std::forward<handler_type>(handler)) (impl, m, timeout_ms);
std::forward<handler_type>(handler))
it makes no sense to forward already decayed type

2021-08-31 10:13 UTC, zagrichanskiy commented on include/dbus/detail/async_send_op.hpp
> +                                             MessageHandler&& handler)
MessageHandler is a class template parameter, so in scope of the constructor it's already a concrete type
MessageHandler&& here is an rvalue reference, not forwarding reference

2021-08-31 10:13 UTC, zagrichanskiy commented on include/dbus/detail/async_send_op.hpp
> +                                             MessageHandler&& handler)
I think it was correct initially

2021-08-31 10:13 UTC, zagrichanskiy commented on include/dbus/connection_service.hpp
> +    return asio::async_initiate<MessageHandler, void(asio::error_code, message)>(std::move(i), h);
to move from lambda you should declare it mutable (however there is nothing to move from it really)

2021-08-31 10:13 UTC, zagrichanskiy commented on include/dbus/detail/queue.hpp
> +    return asio::async_initiate<MessageHandler, void(asio::error_code, message_type)>(std::move(i), h);
mutable if std::move, or remove std::move

2021-08-31 10:13 UTC, zagrichanskiy commented on test/avahi.cpp
> +        [&io]() ->asio::awaitable<void>
auto ex = co_await asio::this_coro::executor
instead of &io

2021-08-31 10:13 UTC, zagrichanskiy commented on test/avahi.cpp
> +            io.stop();
there is no asio::io_context::work created anywhere, stop is not needed

2021-08-31 10:13 UTC, zagrichanskiy commented on test/avahi.cpp
> +            io.stop();
just rethrow for the test to exit with a failure

2021-08-31 10:13 UTC, zagrichanskiy commented on test/avahi.cpp
> +  t.async_wait([&](const asio::error_code& /*e*/) {
remove timer
just invoke io.run_for(10s) instead

2021-08-31 10:13 UTC, zagrichanskiy commented on test/connection.cpp
> +    client.async_send(m, [&io, &test_result] (asio::error_code ec, dbus::message r)
please ensure that library moves a message, otherwise we may perform unneeded copy

2021-09-01 07:48 UTC, yurp commented on test/avahi.cpp
> +            io.stop();
agree with rethrow

2021-09-01 07:48 UTC, yurp commented on include/dbus/connection_service.hpp
> +    return asio::async_initiate<MessageHandler, void(asio::error_code, message)>(std::move(i), h);
agree

2021-09-01 07:48 UTC, yurp commented on CMakeLists.txt
> +target_compile_features(asio-dbus INTERFACE cxx_std_20)
ok

2021-09-01 07:48 UTC, yurp commented on include/dbus/detail/queue.hpp
> +    return asio::async_initiate<MessageHandler, void(asio::error_code, message_type)>(std::move(i), h);
ok

2021-09-01 07:48 UTC, yurp commented on test/avahi.cpp
> +  t.async_wait([&](const asio::error_code& /*e*/) {
ok

2021-09-01 07:48 UTC, yurp commented on test/avahi.cpp
> +        [&io]() ->asio::awaitable<void>
done

2021-09-01 07:48 UTC, yurp commented on test/avahi.cpp
> +            io.stop();
done

2021-09-01 07:48 UTC, yurp commented on test/connection.cpp
> +    client.async_send(m, [&io, &test_result] (asio::error_code ec, dbus::message r)
looks risky, let's copy so far

2021-09-01 07:48 UTC, yurp commented on include/dbus/detail/async_send_op.hpp
> +                                             MessageHandler&& handler)
agree

2021-09-01 07:48 UTC, yurp commented on include/dbus/connection_service.hpp
> +      detail::async_send_op<handler_type>(this->get_io_context(), std::forward<handler_type>(handler)) (impl, m, timeout_ms);
thanks

2021-09-01 08:51 UTC, pernatiy approved these changes

2021-09-01 08:51 UTC, pernatiy commented on test/connection.cpp
> +    client.async_send(m, [&io, &test_result] (asio::error_code ec, dbus::message r)
dbus::message is a shared pointer holder

2021-09-01 08:52 UTC, merged